### ISSUE TITLE
Network on system not working anymore after hours

### ISSUE THREAD

**Issue by Tidos2** [adocilesloth/TS3StudioPlugin2#3]
Hi,

i use your plugin for some days now and the last few days i recognized some network connection error problems on my system. First i thought it is a windows problem with some drivers or other stuff but now i think the problem is in the plugin.

I stream with obs some hours and the plugin is active. The TS Client is not running on the system. After these hours i get a connection error in game and new connections wont able to establish. Neither in game nor in browser or other software. Running connections are fine until they get closed so no new can be established.

If i try to lookup dns entries it works fine, also ping to some servers with ip or dns. The Tool Process Hacker shows me that obs want to connect local every second and cant reach the goal. Maybe after some hours a pool of open connections or others stuff is running to the limit and no new connections can be established. If that is the problem then you should programm to close a failed connection try safely.

Greeting Tidos

**Comment by adocilesloth** [comment]
Hi,

Have you tried disabling the plugin when you aren't using it?

Cheers,
Sloth

On 31 Aug 2017 19:07, "Tidos2" <notifications@github.com> wrote:

Hi,

i use your plugin for some days now and the last few days i recognized some
network connection error problems on my system. First i thought it is a
windows problem with some drivers or other stuff but now i think the
problem is in the plugin.

I stream with obs some hours and the plugin is active. The TS Client is not
running on the system. After these hours i get a connection error in game
and new connections wont able to establish. Neither in game nor in browser
or other software. Running connections are fine until they get closed so no
new can be established.

If i try to lookup dns entries it works fine, also ping to some servers
with ip or dns. The Tool Process Hacker shows me that obs want to connect
local every second and cant reach the goal. Maybe after some hours a pool
of open connections or others stuff is running to the limit and no new
connections can be established. If that is the problem then you should
programm to close a failed connection try safely.

Greeting Tidos

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adocilesloth/TS3StudioPlugin2/issues/3>, or mute the
thread

**Comment by Tidos2** [comment]
Yes if i disable it, the connection errors are gone.

**Comment by adocilesloth** [comment]
Then you have your solution.

On 31 Aug 2017 20:29, "Tidos2" <notifications@github.com> wrote:

Yes if i disable it, the connection errors are gone.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/adocilesloth/TS3StudioPlugin2/issues/3#issuecomment-326256003>,
or mute the thread

**Comment by Tidos2** [comment]
This is not the solution for the problem. It is a work around. You have a clean up bug in your code.

**Comment by Bigdeath** [comment]
Wow. Good thing I read that. Now I know why I get a network problem after 5h with OBS if TS3 is not running but the overlay is active. Maybe it would be good to declare it as KnownIssue.
